name: Build Kivy APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: 设置 Python 环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: 安装系统编译依赖
      run: |
        sudo apt update
        sudo apt install -y zip unzip build-essential git python3-dev ffmpeg libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev
        
    - name: 安装打包工具
      run: |
        pip install --upgrade cython virtualenv buildozer
        
    - name: 开始编译 APK
      run: |
        buildozer android debug
        
    - name: 上传编译好的 APK
      uses: actions/upload-artifact@v3
      with:
        name: Omphalos-APK
        path: bin/*.apk
